### ISSUE TITLE
Irina - Google Ads

### ISSUE THREAD

**Issue by ToniAmor** [ToniAmor/SG-Tasks#17]

**Comment by ToniAmor** [comment]
•Run Ads for Men Products
•Ask about Keywords
•Suggest Hyperpigmentation and Cold Weather and Dry Skin

**Comment by ToniAmor** [comment]
•Separate campaign for Serum

**Comment by ToniAmor** [comment]
•Are we running Ads for Men?

**Comment by ToniAmor** [comment]
• Separate campaign for Men's Cleanser

**Comment by ToniAmor** [comment]
0.9 ROAS

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/208166862-268b8d9a-f154-446c-8770-81b5aa0829fc.png)

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/208167024-8fb28bf2-ad41-45b2-90bc-a35266730508.png)

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/209084328-a65874db-d9d3-42ba-bae5-81e3bad1e11f.png)

**Comment by ToniAmor** [comment]
• Update Search Ads Copies and Images

**Comment by ToniAmor** [comment]
• EOW create campaigns for new products

**Comment by ToniAmor** [comment]
Setup BodyScrub campaign

**Comment by ToniAmor** [comment]
Ask Irina to give access to sheet to Muhammad.

**Comment by ToniAmor** [comment]
How do we know if products will sell to Canada and Mexico.

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/212266080-931b3883-cad4-42e8-b902-fd240b31d410.png)

**Comment by ToniAmor** [comment]
Run campaign for Bodywash.

**Comment by ToniAmor** [comment]
•Ad Spend should be higher for PMax

**Comment by ToniAmor** [comment]
• why isn't it spending 400 Irina

**Comment by ToniAmor** [comment]
• Pause Amazon Exfoliator Ad

**Comment by ToniAmor** [comment]
• Headsup that Ads are not spending all the budget.

**Comment by ToniAmor** [comment]
• Spend the full amount - Ad Budget (Daily)

**Comment by ToniAmor** [comment]
• Serum - Mark as Sold Out (What is the ROAS)

**Comment by ToniAmor** [comment]
• Om Keywords

**Comment by Oprahulsharma** [comment]
**KEYWORDS**

body wash sensitive skin
sensitive skin body wash
mole remover for body
body wash women
skin tag removal
mole remover
crema para las manchas de la cara
dark spot corrector
dark spot remover for body
ambi fade cream for dark spots
skin tag remover freeze off
hyperpigmentation treatment
capcut
acne body wash
body skin care products
faded topicals for dark spots
hydroquinone cream for dark spots
musely dark spot cream
acne body wash
body skin care products
faded topicals for dark spots
tumeric soap, acne, dark spots, hyperpigmentation, smooth skin

**Comment by ToniAmor** [comment]
• Launch Ad campaign in Canada

**Comment by Oprahulsharma** [comment]
SWAP BODY WASH WITH PMAX?

**Comment by ToniAmor** [comment]
• Spend more on pmax campaign since it never goes under 1.5

**Comment by ToniAmor** [comment]
• Run Amazon Ad - Bodywash, Serum and Exfoliator

**Comment by ToniAmor** [comment]
• ROAS

**Comment by ToniAmor** [comment]
• Ihor notes to Irina

**Comment by ToniAmor** [comment]
• organize call with Irina and Muhammad: what should be the targets for the ad account

**Comment by ToniAmor** [comment]
Canada

Google Ads campaign for each products
Amazon Ads for each products
Check if feed is needed or not for Google Ads Canada
Add Items to Previous campaigns
