### ISSUE TITLE
Music Channel Issue 

### ISSUE THREAD

**Issue by ToniAmor** [ToniAmor/SG-Tasks#4]
Spotify strategy and budget
https://docs.google.com/document/d/1DlG9u3MGv7V3dJukBAc2ZMko-ZjjlqPphxAVbCC-G5M/edit?usp=sharing
Plan and Budget for Spotify
Find a Lyric Artist / SG Animation
Upload music audio to YT / Lyric Video for WWW and You're My Baby
Submit to music playlists
https://portal.mrsuicidesheep.com/signup
Submit 'Love on the Range'
Submit 'For You'
Submit Music - You're My Baby
Email: ohlord@fredscarf.com
Password: Fredscarf01!
Set up an account with https://portal.mrsuicidesheep.com/signup
Figure out how to submit to - https://spinninrecords.com/playlists/
Getting an error submitting music:
SPINNIN RECORDS - Google Docs
Submit Music - You're My Baby
Spinnin' Records | World's leading dance label and community. (spinninrecords.com)
Username: fredscarf
Password: Fredscarf01!
Email: ohlord@fredscarf.com
Email Password: MuscleGod69
•Create a Profile for Spinnin Records.
Spinnin' Records | World's leading dance label and community. (spinninrecords.com)
https://www.youtube.com/c/EscapeMusicYT/about
SyrebralVibes - YouTube
Find more playlist like this
make sure website is up to date for Music.
Change cream to body section
https://instamber.com/buy-spotify-monthly-listeners
Find competitors for cheapest monthly listeners - spotify
•Ask site if they can keep Monthly listeners to be permanent.
Add spotify plays and streams
Spotify - Google Sheets
Make a spreadsheet and find the cheapest site. 
Spotify Publishers
Playlisting Services
SoundCampaign - The #1 Playlists Music Pitching Platform (soundcamps.com)
PROMOTE A SPOTIFY PLAYLIST • Soundplate.com
Create a profile in Musosoup
Your Music Deserves The Best | MySphera
•RepostExchange - We help artists get heard
Create a profile in Repost
The 10 Best Playlisting Services for Growing Your Audience | LANDR Blog
Create profile - https://www.submithub.com/submit
Username: FredScarf
Password: Fredscarf1
https://flowsty.com/ 
New Song - Musosoup
Plays
https://www.likeservice24.com/spotify/plays/
https://artistpush.me/collections/spotify-promotion
20% OFF
https://buysocialtoday.com/spotify/spotify-plays/
best deal
https://www.bestsellermarket.com/collections/spotify
https://viralyft.com/buy-spotify-plays
10,000,000
https://thesocialmediagrowth.com/services/spotify
https://www.trackplaylists.com/join?gclid=CjwKCAiAqIKNBhAIEiwAu_ZLDq7uMvJeey8Vw7vWNTd8-FMFkBgp2ntYX8aj02oGX4_lVBB86OHujBoCa9sQAvD_BwE
https://streamingfamous.com/buy-spotify-plays/?utm_source=google&utm_medium=cpc&utm_campaign=sf&utm_term=buy%20spotify%20streams&gclid=CjwKCAiAqIKNBhAIEiwAu_ZLDkNPn7SpRtvauAuyR0m1Vl7mQKfOyDT1p3FoTIUseeiorrULtaEssxoC2iwQAvD_BwE 
monthly listeners
Celesta
StreamingFamous
Music for DJs
 – https://www.beatsource.com/genre/rock/8 
Start Lyric Videos - Ask Nihat for After Effects Template for Lyric Videos
Upload  Worship song
Upload Manwhore to AWAL

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/207123670-3c685248-925a-42ca-8e73-68e6953e6a80.png)

Reminder: you need to provide your banking and tax information in order to receive payouts.
Click here to enter your details in the Banking and Tax app

**Comment by ToniAmor** [comment]
https://www.yougrowpromo.com/spotify

**Comment by ToniAmor** [comment]
https://top4smm.com/

**Comment by ToniAmor** [comment]
nihat-- album art + audio for MIA

**Comment by ToniAmor** [comment]
• Setup M.I.A  Ad $5 - Keywords for Music

**Comment by ToniAmor** [comment]
• Cover Audio Video - For you, Manwhore, Wild Wild West

**Comment by ToniAmor** [comment]
• Ask Awal about how we should introduce them for the Magazine interview. 
• Ask for the correct phrasing. 
(Distribution/Signed Contract with Awal)


hey! fred is about to do an interview with a magazine and they will ask for updates. What should he say his relationship with awal is? should he say he signed with AWAL or is now with awal? whats the correct phrasing?


![image](https://user-images.githubusercontent.com/79007813/217462051-e8c07616-6dd1-4b0d-a89f-156ba37c244b.png)

**Comment by ToniAmor** [comment]
• What other famous Artists distributes their music in Awal like  Mumford and Sons
The magazines wants to have a reference. 

![image](https://user-images.githubusercontent.com/79007813/218787261-d69ead09-913a-4259-90c4-12b830483c6a.png)

**Comment by ToniAmor** [comment]
![image](https://user-images.githubusercontent.com/79007813/219288358-d6a93ae7-97c0-4295-adec-efd2e7f029d2.png)

**Comment by ToniAmor** [comment]
https://elements.envato.com/comic-slideshow-VV7QSCR

**Comment by ToniAmor** [comment]
• Om helps with AWAL about Youtube OAC

**Comment by Oprahulsharma** [comment]
Spotify Monthly Listeners Promotion

**Comment by Oprahulsharma** [comment]
https://www.ticketmaster.com
